//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by s8tune.rc
//
#define IDD_S8TUNE_FORM                 101
#define IDR_MAINFRAME                   128
#define IDR_S8TUNETYPE                  129
#define IDS_PLAYBARRECT                 129
#define IDR_MENU1                       130
#define IDS_SPEEDRECT                   130
#define IDS_SORTRECT                    130
#define IDB_SPEAKER                     131
#define IDS_CENTRECT                    131
#define IDB_PLAY                        132
#define IDS_KEYRECT                     132
#define IDB_PAUSE                       133
#define IDI_SPEAKER                     133
#define IDB_SPEAKER1                    134
#define IDD_RENAME                      134
#define IDB_REWIND                      135
#define IDB_VOLUME                      136
#define IDB_VOLUME1                     137
#define IDD_ADDTHREAD                   137
#define IDB_TOTOP                       138
#define IDB_PLAYPAUSE                   139
#define IDB_RECORD                      139
#define IDB_TONEXT                      139
#define IDB_RECSTOP                     140
#define IDC_CURDROP                     141
#define IDB_TONOW                       146
#define IDD_HELPDLG                     147
#define IDB_MOJI09                      148
#define IDB_SETA                        148
#define IDB_PLAY1                       149
#define IDB_TONEXT1                     150
#define IDB_PAUSE1                      151
#define IDB_TOTOP1                      152
#define IDB_SETB                        153
#define IDB_SAVEAB                      154
#define IDB_RETR                        155
#define IDB_STOP                        156
#define song                            157
#define IDB_KENSONG                     157
#define IDB_KENARTIST                   158
#define IDB_KENPATH                     159
#define IDC_TEMPO                       1000
#define IDC_PITCH                       1001
#define IDC_SAMPLERATE                  1002
#define IDC_PITCHSTR                    1003
#define IDC_RATESTR                     1004
#define IDC_TEMPOSTR                    1005
#define IDC_VOL                         1006
#define IDC_TEMPOSTR2                   1006
#define IDC_SONG                        1007
#define IDC_VOLSTR                      1008
#define IDC_SONGSTR                     1009
#define IDC_SONGLIST                    1010
#define IDC_SCROLLBARKEY                1011
#define IDC_SONGSTR2                    1012
#define IDC_SPIN1                       1013
#define IDC_SONGNAME                    1013
#define IDC_SCROLLBARCENT               1015
#define IDC_SCROLLBARTEMPO              1016
#define IDC_STOP                        1018
#define IDC_START                       1019
#define IDC_PAUSE                       1020
#define IDC_START2                      1021
#define IDC_LIST1                       1022
#define IDC_PAUSE2                      1022
#define IDC_HELPLIST                    1022
#define IDC_HELPLISTBOX                 1022
#define IDC_REWIND                      1023
#define IDC_A2B                         1024
#define IDC_FORWARD                     1024
#define IDC_TONEXT                      1024
#define IDC_REWIND2                     1025
#define IDC_SETA                        1026
#define IDC_RENAME                      1026
#define IDC_SETB                        1027
#define IDC_RENAME2                     1027
#define IDC_SONGNUM                     1028
#define IDC_KENSAKU                     1029
#define IDC_PAUSE1                      1031
#define IDC_KENSAKUSTR                  1032
#define IDC_FULLPATH                    1033
#define IDC_HOZON                       1034
#define IDC_SONGPATH                    1035
#define IDC_RESET1                      1038
#define IDC_RESET2                      1041
#define IDC_RESET3                      1042
#define IDC_PROGRESS1                   1045
#define IDC_HIDEBUTTON                  1046
#define IDC_TONEXT2                     1048
#define IDC_STATICHANNI                 1052
#define IDC_KENSAKUT                    1059
#define IDC_TONOW                       1062
#define IDC_KENSAKUTYPE                 1063
#define IDC_TATSUAKI                    1064
#define IDC_CHANGETAG                   1065
#define IDC_CHANGETAGTXT                1066
#define ID_DELETEONE                    32771
#define ID_DUPLICATE                    32772
#define ID_SHOWPATH                     32773
#define ID_RENAME                       32774
#define ID_ADDFOLDER                    32775
#define ID_DELETEALL                    32776
#define ID_RETURN                       32777
#define ID_ADDFILENAME                  32778
#define ID_ADDFILE1                     32781
#define IDC_RECORDCTL                   32782
#define IDC_BASSRECORD                  32783
#define IDC_WAVERECORD                  32783
#define IDC_STOPRECORD                  32784
#define IDC_WMARECORD                   32784
#define ID_KEY_A                        32786
#define IDC_MP3RECORD                   32787
#define ID_ACCEL32790                   32790
#define ID_DUPLICATETOP                 32791
#define IDC_TOCUSONG                    32792
#define ID_ADDFILES                     32794
#define IDC_REPEATON                    32795
#define IDC_REPEATOFF                   32796
#define IDC_RENZOKU                     32797
#define IDC_RENZOKUREPEAT               32798
#define ID_CTRL_A                       32799
#define ID_CTRL_S                       32800
#define ID_CTRL_D                       32801
#define ID_CTRL_F                       32802
#define ID_CTRL_G                       32803
#define ID_CTRL_Z                       32804
#define ID_HELPDLG                      32805

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
